version: '3'
services:
  icoop:
    build:
      context: ./icoop
      dockerfile: Dockerfile
    volumes:
      - ./icoop:/var/www/html/
    depends_on:
      - database
    networks:
      codeigniter_net:
    ports:
      - "8181:80"
    restart: always

#  icoop-portal:
#    build:
#      context: ./icoop-portal
#      dockerfile: Dockerfile
#    volumes:
#      - ./icoop-portal:/var/www/html/
#    depends_on:
#      - database
#    networks:
#      codeigniter_net:
#    ports:
#      - "8080:80"
#    restart: always

  database:
    platform: linux/x86_64
    image: mysql:5.7
    networks:
      codeigniter_net:
    ports:
      - '3306:3306'
    volumes:
      - ./icoop.sql:/docker-entrypoint-initdb.d/icoop.sql
    env_file:
      - .env

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8283:80'
    env_file:
      - .env
    networks:
      codeigniter_net:
networks:
  codeigniter_net:
